### ISSUE TITLE
Please change "Hello World" in line 44 to something else

### ISSUE THREAD

**Issue by digitalseth** [thegeekkid/Space_java#2]

**Comment by thegeekkid** [comment]
What would you suggest?

**Comment by digitalseth** [comment]
I added your name. You can try changing it to my name.

**Comment by thegeekkid** [comment]
It has been updated.

**Comment by digitalseth** [comment]
Very nice job.

**Comment by thegeekkid** [comment]
Lol.  Thanks.

I think we already did some of this.  Just delete some random comment I guess.  ;)

**Comment by digitalseth** [comment]
You need to put an issue on MY repo now.

**Comment by thegeekkid** [comment]
Lol.  will do.

**Comment by thegeekkid** [comment]
Done.

**Comment by digitalseth** [comment]
I don't think you put an issue on mine.

**Comment by thegeekkid** [comment]
No, he said to commit without doing a commit.
